# Generated by Django 5.2.1 on 2025-10-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("private", "Only I can see this"),
                    ("public", "Anyone can see this"),
                ],
                default="private",
                max_length=50,
            ),
        ),
    ]
