# Generated by Django 5.2.1 on 2025-10-21 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_privacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("abbreviation", models.CharField(max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weight", "Weight"),
                            ("volume", "Volume"),
                            ("count", "Count"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_conversion_factor", models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_type", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.unit"
            ),
        ),
    ]
