# Generated by Django 5.2.1 on 2025-10-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_unit_uploadedfile_alter_recipeingredient_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="system",
            field=models.CharField(
                choices=[("metric", "Metric"), ("imperial", "Imperial")],
                default="metric",
                max_length=10,
            ),
        ),
    ]
