# Generated by Django 5.2.1 on 2025-10-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_unit_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="is_base_unit",
            field=models.BooleanField(default=False),
        ),
    ]
