# Generated by Django 5.2.1 on 2025-10-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_unit_is_base_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="allergens",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="nutritional_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
