# Generated by Django 5.2.1 on 2025-10-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_ingredient_allergens_ingredient_nutritional_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="is_optional",
            field=models.BooleanField(default=False),
        ),
    ]
