INGREDIENTS = [
    {"name": "apple", "nutritional_info": {}, "allergens": []},
    {"name": "banana", "nutritional_info": {}, "allergens": []},
    {"name": "flour", "nutritional_info": {}, "allergens": ["gluten"]},
    {"name": "cornstarch", "nutritional_info": {}, "allergens": []},
    {"name": "milk", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "eggs", "nutritional_info": {}, "allergens": ["eggs"]},
    {"name": "sugar", "nutritional_info": {}, "allergens": []},
    {"name": "salt", "nutritional_info": {}, "allergens": []},
    {"name": "butter", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "olive oil", "nutritional_info": {}, "allergens": []},
    {"name": "onion", "nutritional_info": {}, "allergens": []},
    {"name": "garlic", "nutritional_info": {}, "allergens": []},
    {"name": "tomato", "nutritional_info": {}, "allergens": []},
    {"name": "chicken breast", "nutritional_info": {}, "allergens": []},
    {"name": "beef", "nutritional_info": {}, "allergens": []},
    {"name": "carrot", "nutritional_info": {}, "allergens": []},
    {"name": "potato", "nutritional_info": {}, "allergens": []},
    {"name": "rice", "nutritional_info": {}, "allergens": []},
    {"name": "pasta", "nutritional_info": {}, "allergens": ["gluten"]},
    {"name": "cheddar cheese", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "yogurt", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "honey", "nutritional_info": {}, "allergens": []},
    {"name": "lemon", "nutritional_info": {}, "allergens": []},
    {"name": "lime", "nutritional_info": {}, "allergens": []},
    {"name": "cucumber", "nutritional_info": {}, "allergens": []},
    {"name": "bell pepper", "nutritional_info": {}, "allergens": []},
    {"name": "spinach", "nutritional_info": {}, "allergens": []},
    {"name": "kale", "nutritional_info": {}, "allergens": []},
    {"name": "broccoli", "nutritional_info": {}, "allergens": []},
    {"name": "cauliflower", "nutritional_info": {}, "allergens": []},
    {"name": "mushroom", "nutritional_info": {}, "allergens": []},
    {"name": "cabbage", "nutritional_info": {}, "allergens": []},
    {"name": "zucchini", "nutritional_info": {}, "allergens": []},
    {"name": "eggplant", "nutritional_info": {}, "allergens": []},
    {"name": "avocado", "nutritional_info": {}, "allergens": []},
    {"name": "strawberry", "nutritional_info": {}, "allergens": []},
    {"name": "blueberry", "nutritional_info": {}, "allergens": []},
    {"name": "raspberry", "nutritional_info": {}, "allergens": []},
    {"name": "blackberry", "nutritional_info": {}, "allergens": []},
    {"name": "watermelon", "nutritional_info": {}, "allergens": []},
    {"name": "melon", "nutritional_info": {}, "allergens": []},
    {"name": "peach", "nutritional_info": {}, "allergens": []},
    {"name": "pear", "nutritional_info": {}, "allergens": []},
    {"name": "plum", "nutritional_info": {}, "allergens": []},
    {"name": "cherry", "nutritional_info": {}, "allergens": []},
    {"name": "grape", "nutritional_info": {}, "allergens": []},
    {"name": "pineapple", "nutritional_info": {}, "allergens": []},
    {"name": "mango", "nutritional_info": {}, "allergens": []},
    {"name": "papaya", "nutritional_info": {}, "allergens": []},
    {"name": "coconut", "nutritional_info": {}, "allergens": ["tree nuts"]},
    {"name": "almond", "nutritional_info": {}, "allergens": ["tree nuts"]},
    {"name": "walnut", "nutritional_info": {}, "allergens": ["tree nuts"]},
    {"name": "cashew", "nutritional_info": {}, "allergens": ["tree nuts"]},
    {"name": "peanut", "nutritional_info": {}, "allergens": ["peanuts"]},
    {"name": "hazelnut", "nutritional_info": {}, "allergens": ["tree nuts"]},
    {"name": "pecan", "nutritional_info": {}, "allergens": ["tree nuts"]},
    {"name": "bacon", "nutritional_info": {}, "allergens": []},
    {"name": "sausage", "nutritional_info": {}, "allergens": []},
    {"name": "salmon", "nutritional_info": {}, "allergens": ["fish"]},
    {"name": "tuna", "nutritional_info": {}, "allergens": ["fish"]},
    {"name": "shrimp", "nutritional_info": {}, "allergens": ["shellfish"]},
    {"name": "crab", "nutritional_info": {}, "allergens": ["shellfish"]},
    {"name": "lobster", "nutritional_info": {}, "allergens": ["shellfish"]},
    {"name": "cod", "nutritional_info": {}, "allergens": ["fish"]},
    {"name": "tilapia", "nutritional_info": {}, "allergens": ["fish"]},
    {"name": "soy sauce", "nutritional_info": {}, "allergens": ["soy"]},
    {"name": "tofu", "nutritional_info": {}, "allergens": ["soy"]},
    {"name": "rice vinegar", "nutritional_info": {}, "allergens": []},
    {"name": "balsamic vinegar", "nutritional_info": {}, "allergens": []},
    {"name": "olive oil", "nutritional_info": {}, "allergens": []},
    {"name": "vegetable oil", "nutritional_info": {}, "allergens": []},
    {"name": "canola oil", "nutritional_info": {}, "allergens": []},
    {"name": "sunflower oil", "nutritional_info": {}, "allergens": []},
    {"name": "bread", "nutritional_info": {}, "allergens": ["gluten"]},
    {"name": "baguette", "nutritional_info": {}, "allergens": ["gluten"]},
    {"name": "pita", "nutritional_info": {}, "allergens": ["gluten"]},
    {"name": "yeast", "nutritional_info": {}, "allergens": []},
    {"name": "baking powder", "nutritional_info": {}, "allergens": []},
    {"name": "baking soda", "nutritional_info": {}, "allergens": []},
    {"name": "cocoa powder", "nutritional_info": {}, "allergens": []},
    {"name": "chocolate", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "dark chocolate", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "white chocolate", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "vanilla extract", "nutritional_info": {}, "allergens": []},
    {"name": "basil", "nutritional_info": {}, "allergens": []},
    {"name": "oregano", "nutritional_info": {}, "allergens": []},
    {"name": "thyme", "nutritional_info": {}, "allergens": []},
    {"name": "rosemary", "nutritional_info": {}, "allergens": []},
    {"name": "parsley", "nutritional_info": {}, "allergens": []},
    {"name": "cilantro", "nutritional_info": {}, "allergens": []},
    {"name": "chili pepper", "nutritional_info": {}, "allergens": []},
    {"name": "black pepper", "nutritional_info": {}, "allergens": []},
    {"name": "cinnamon", "nutritional_info": {}, "allergens": []},
    {"name": "nutmeg", "nutritional_info": {}, "allergens": []},
    {"name": "clove", "nutritional_info": {}, "allergens": []},
    {"name": "ginger", "nutritional_info": {}, "allergens": []},
    {"name": "turmeric", "nutritional_info": {}, "allergens": []},
    {"name": "mustard", "nutritional_info": {}, "allergens": ["mustard"]},
    {"name": "ketchup", "nutritional_info": {}, "allergens": []},
    {"name": "mayonnaise", "nutritional_info": {}, "allergens": ["eggs"]},
    {"name": "vinegar", "nutritional_info": {}, "allergens": []},
    {"name": "cream", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "sour cream", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "yogurt", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "cream cheese", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "parmesan", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "mozzarella", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "feta", "nutritional_info": {}, "allergens": ["milk"]},
    {"name": "blue cheese", "nutritional_info": {}, "allergens": ["milk"]},
]
